### ISSUE TITLE
Anyword on when this will be available?

### ISSUE THREAD

**Issue by Troubadoure** [passepartoutvpn/passepartout-macos#1]
As title says - webpage still says 'coming soon' Would be good to know when this will be available for the mac. Love the iOS app which I use on a regular basis for my iPhone and iPad but have to keep flicking between tunnelblick and vicosity which just don't do the job as well as Passepartout does. Fingers crossed it will be sometime soon!

**Comment by keeshux** [comment]
There's relevant work on it, yet I'm unable to disclose any concrete ETA. macOS is quite more complicated, there are many variables involved and it's not the only project I'm working on. I'd certainly like to build something decent within the end of the year, but it's a wish more than a plan.

Anyway, you should join the subreddit for any update on the topic -there will be as soon as I have:

https://www.reddit.com/r/passepartout
