### ISSUE TITLE
Support per-app configuration

### ISSUE THREAD

**Issue by fumoboy007** [passepartoutvpn/passepartout-macos#3]
(I know you haven’t released the macOS version yet; just sending in an early feature request! 😀)

Some VPN apps support routing traffic only for a user-specified subset of apps. One use case is to route only traffic from a BitTorrent app through the VPN.

## Implementation

The NetworkExtension framework seems to support per-app configuration. However, all (almost all?) of the existing VPN apps do not use this infrastructure. Building on top of this infrastructure would allow the Passepartout macOS app to support this functionality in the Mac App Store.

**Comment by keeshux** [comment]
AFAIK it only exists for managed profiles. Probably not even for custom VPN protocols, only via configuration profiles.

**Comment by fumoboy007** [comment]
Looks like this functionality was just released in macOS 10.15.4.

1. Create a per-app VPN using [`NETunnelProviderManager.forPerAppVPN()`](https://developer.apple.com/documentation/networkextension/netunnelprovidermanager/3543407-forperappvpn).
2. Configure [app rules](https://developer.apple.com/documentation/networkextension/netunnelprovidermanager/3524238-apprules), [Calendar domains](https://developer.apple.com/documentation/networkextension/netunnelprovidermanager/3524239-calendardomains), [Contacts domains](https://developer.apple.com/documentation/networkextension/netunnelprovidermanager/3524240-contactsdomains), [Mail domains](https://developer.apple.com/documentation/networkextension/netunnelprovidermanager/3524242-maildomains), and [Safari domains](https://developer.apple.com/documentation/networkextension/netunnelprovidermanager/3524243-safaridomains).

**Comment by keeshux** [comment]
> Per-App VPN
> The only way to configure Per-App VPN is by enrolling the device in a Mobile Device Management (MDM) system
